#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2020 Dominik Salvet
# https://github.com/dominiksalvet/nconv
#-------------------------------------------------------------------------------

echo 'copying files'
mkdir -p /usr/local/bin/ &&
cp src/nconv /usr/local/bin/
