#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2020-2021 Dominik Salvet
# https://github.com/dominiksalvet/nconv
#-------------------------------------------------------------------------------

echo 'copying files' &&
mkdir -p "$HOME/.local/bin/" &&
cp src/nconv "$HOME/.local/bin/"
