#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2020 Dominik Salvet
# https://github.com/dominiksalvet/nconv
#-------------------------------------------------------------------------------

echo 'removing files'
rm -f /usr/local/bin/nconv
