#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2020-2021 Dominik Salvet
# https://github.com/dominiksalvet/nconv
#-------------------------------------------------------------------------------

echo 'removing files' &&
rm -f /usr/local/bin/nconv
