#-------------------------------------------------------------------------------
# Copyright 2020 Dominik Salvet
# https://github.com/dominiksalvet/nconv
#-------------------------------------------------------------------------------

name: CI
on: [push, pull_request]

jobs:
  Analysis:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout commit
      uses: actions/checkout@v2

    - name: Check shellcheck
      run: shellcheck --version

    - name: Check source files
      run: shellcheck src/nconv

    - name: Check install files
      run: shellcheck .install/*
